### ISSUE TITLE
Redis QA

### ISSUE THREAD

**Issue by zbal** [wiredcraft-ops/role-wcl-zabbix-scripts#3]
A few comments and required changes:
- Need comments and docinfo
- Need config file (INI config file for example)
- Why buffer size of 500 instead of regular 2^ values like 512 / 1024 etc.
- Need proper try/except to handle the cases where:
  - redis not running / timeout on connect
  - key is missing from the response
- Fetch `info all` instead of `info` only
- Consider using also `auth PASS` before submitting the `info` request - try without, then on failure, try with

**Comment by sunsongxp** [comment]
About the support of using auth in redis when getting info, we can do this in case the redis is set with password. But setting password in redis itself does not make sense. As far as I know, redis does not support any end to end encryption to assure the password is encrypted when transferring. What's more, redis can be brutal forced attacked. The thing is, if the connection between client and redis server is safe, we do not need setting a password, if not, what redis provide is not secure enough. I recommend not using password in redis

**Comment by sunsongxp** [comment]
done except config file.
