### ISSUE TITLE
php-fpm QA

### ISSUE THREAD

**Issue by zbal** [wiredcraft-ops/role-wcl-zabbix-scripts#4]
- Need comments
- Need config file
- Need to configure the page to check (`/status`)
- Need to support UNIX socket instead of TCP only
- Proper try / except for when:
  - cgi-bin binary not present
  - php-fpm not running
  - key is not present

**Comment by sunsongxp** [comment]
I have difficulty supporting unix socket.

**Comment by sunsongxp** [comment]
Close this and move things left to issue #6
